version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: gpt-oss-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data:/root/.ollama
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - llm-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: gpt-oss-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - llm-network

  embeddings:
    build:
      context: .
      dockerfile: docker/Dockerfile.embeddings
    container_name: gpt-oss-embeddings
    ports:
      - "8001:8001"
    volumes:
      - ./documents:/app/documents
      - ./config/embeddings:/app/config
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_HOST=http://qdrant:6333
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge