version: '3.8'

services:
  ollama:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gpt-oss-ollama
    ports:
      - "11434:11434"
    volumes:
      - ../data:/root/.ollama
      - ../config:/app/config
      - ../logs:/app/logs
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge